name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    permissions:
      contents: write
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64
          - os: macos-14
            target: aarch64

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.19.2

      - name: Build wheels
        run: |
            cd medra_pybind
            python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.11,<3.12"
          CIBW_SKIP: "*-win32 *-musllinux_* *_i686"

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: medra_pybind/wheelhouse/

      - if: github.ref == 'refs/heads/main'
        name: update prerelease tag
        uses: EndBug/latest-tag@v1.6.1
        with:
          ref: "prerelease"

  prerelease:
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: push-${{ github.ref_name }}-prerelease
      cancel-in-progress: true
    needs: [build_wheels]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: medra_pybind/wheelhouse/

      - name: GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          tag: "prerelease"
          name: "Development Build"
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          makeLatest: true
          artifacts: "medra_pybind/wheelhouse/*"

  release:
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [build_wheels]
    concurrency:
      group: push-${{ github.ref_name }}-release
      cancel-in-progress: true
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: medra_pybind/wheelhouse/

      - name: GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: "Release ${{ github.ref_name }}"
          tag: ${{ github.ref_name }}
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          makeLatest: true
          artifacts: "medra_pybind/wheelhouse/*"
